modLoader="javafml"
loaderVersion="[47,)"
license="GPL-2.0"

[[mods]]
modId="betterclue"
version="${version}"
displayName="BetterClue"
logoFile="assets/betterclue/icon.png"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.betterclue]]
modId="forge"
mandatory=true
versionRange="[47.4.22,)"
ordering="NONE"
side="BOTH"

[[dependencies.betterclue]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
