plugins {
	id 'dev.architectury.loom' version '1.10.455' apply false
	id 'architectury-plugin' version '3.4.164'
	id 'com.gradleup.shadow' version '8.3.11' apply false
}

architectury {
	minecraft = project.minecraft_version
}

layout.buildDirectory = file('.gradle/root-build')

allprojects {
	group = project.maven_group
	version = project.mod_version
}

tasks.register('collectJars', Copy) {
	dependsOn ':fabric:remapJar', ':neoforge:remapJar'
	from { [project(':fabric').tasks.remapJar.archiveFile, project(':neoforge').tasks.remapJar.archiveFile] }
	into 'dist'
}

subprojects {
	apply plugin: 'dev.architectury.loom'
	apply plugin: 'architectury-plugin'

	base {
		archivesName = "betterclue-${project.name}-${rootProject.minecraft_version}"
	}

	repositories {
		maven { url = 'https://maven-central.storage-download.googleapis.com/maven2/' }
		maven { url = 'https://maven.fabricmc.net/' }
		maven { url = 'https://maven.neoforged.net/releases/' }
		maven { url = 'https://maven.architectury.dev/' }
	}

	repositories.withType(MavenArtifactRepository).configureEach { repo ->
		if (repo.url.toString().startsWith('https://repo.maven.apache.org') || repo.url.toString().startsWith('https://repo1.maven.org')) {
			repo.url = 'https://maven-central.storage-download.googleapis.com/maven2/'
		}
	}

	loom {
		silentMojangMappingsLicense()
		mixin {
			useLegacyMixinAp = false
		}
	}

	dependencies {
		minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
		mappings loom.officialMojangMappings()
	}

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(21)
		}
	}

	tasks.withType(JavaCompile).configureEach {
		options.encoding = 'UTF-8'
	}

	tasks.matching { it.name == 'build' }.configureEach {
		finalizedBy rootProject.tasks.named('collectJars')
	}
}
