org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.problems.report=false
org.gradle.warning.mode=all

mod_version=1.0.0
maven_group=cn.erindax
archives_name=betterclue
enabled_platforms=fabric,neoforge

minecraft_version=1.21.4
java_version=21

fabric_loader_version=0.19.5
fabric_api_version=0.119.4+1.21.4
neoforge_version=21.4.158
