modLoader="javafml"
loaderVersion="[4,)"
license="GPL-2.0"

[[mods]]
modId="betterclue"
version="${version}"
displayName="BetterClue"
logoFile="assets/betterclue/icon.png"

[[mixins]]
config="betterclue.mixins.json"

[[dependencies.betterclue]]
modId="neoforge"
type="required"
versionRange="[21.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.betterclue]]
modId="minecraft"
type="required"
versionRange="[1.21.4,1.21.5)"
ordering="NONE"
side="BOTH"
