modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="betterclue"
version="${version}"
displayName="更好的线索"
logoFile="assets/betterclue/icon.png"
authors="202037994@qq.com"
description='''更好的线索'''

[[mixins]]
config="betterclue.mixins.json"

[[dependencies.betterclue]]
modId="neoforge"
type="required"
versionRange="[21.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.betterclue]]
modId="minecraft"
type="required"
versionRange="[1.21.4,1.21.5)"
ordering="NONE"
side="BOTH"
